### ISSUE TITLE
No addQueryItem member function of QUrl in Qt 5 any more

### ISSUE THREAD

**Issue by CsatiZoltan** [pavlonion/qtcurl#1]
The building of the library is successful but the example usage fails as *addQueryItem* is removed from *QUrl*. Could you update the example to work with Qt 5 too?

**Comment by carlos22** [comment]
Replace `url.addQueryItem("id", "42");` with
```cpp
QUrlQuery query;
query.addQueryItem("id", "42");
url.setQuery(query);
```

**Comment by CsatiZoltan** [comment]
Thank you. Now the error is at the line `opt[CURLOPT_URL] = url;` with the error message
```
no match for ‘operator=’ (operand types are ‘QVariant’ and ‘QUrlQuery’)
     opt[CURLOPT_URL] = url;
                      ^
```

**Comment by carlos22** [comment]
You should not replace the url with QUrlQuery, only the sinle line of `ulr.addQueryItem()` needs to be replaced. So `url` it self needs to be still of type QUrl.

**Comment by CsatiZoltan** [comment]
Thanks for the quick response. The code runs but cannot fetch from example.com
```
"Error: HTTP response code said error
Buffer: The requested URL returned error: 411 Length Required" 
```
